Repository wrtnlabs/agentica, pull requests merged in 2025-02, with the labels that each got.

#1 Create README.md
  README.md
Labels: enhancement

#3 Direct executor of class controller
  src/chatgpt/ChatGptExecuteFunctionAgent.ts
  src/structures/IWrtnAgentController.ts
Labels: enhancement

#4 Add principles chapter on README
  README.md
Labels: documentation, enhancement

#6 Rebuild website.yml
  .github/workflows/website.yml
Labels: documentation

#7 The new chapter Roadmap on README
  README.md
Labels: documentation, enhancement

#9 Fix some typos and complement validation feedback story.
  README.md
  assets/logo.pptx
Labels: bug, documentation

#10 New optimization chapter and pseudo code in validation feedback section.
  README.md
  assets/logo.pptx
Labels: documentation

#11 Docs: contributing doc
  CONTRIBUTING.md
  package.json
Labels: documentation

#17 Fix README DTO bebchmark links
  README.md
Labels: bug, documentation

#20 Add websocket interaction module
  README.md
  package.json
  src/module.ts
  src/rpc/IWrtnAgentRpcListener.ts
  src/rpc/IWrtnAgentRpcService.ts
  src/rpc/WrtnAgentRpcService.ts
  test/examples/websocket.client.ts
  test/examples/websocket.server.ts
Labels: documentation, enhancement

#29 Remove websocket section from roadmap chapter
  README.md
Labels: documentation

#33 `IWrtnAgentRpcListener.initialize()` and test websocket module.
  package.json
  src/rpc/IWrtnAgentRpcListener.ts
  src/rpc/WrtnAgentRpcService.ts
  test/features/test_base_websocket.ts
  test/index.ts
Labels: documentation, enhancement

#40 LLM function selection benchmark
  .github/workflows/build.yml
  packages/agent/.gitignore
  packages/agent/package.json
  packages/agent/src/WrtnAgent.ts
  packages/agent/src/benchmark/select/IWrtnAgentSelectBenchmarkEvent.ts
  packages/agent/src/benchmark/select/IWrtnAgentSelectBenchmarkResult.ts
  packages/agent/src/benchmark/select/IWrtnAgentSelectBenchmarkScenario.ts
  packages/agent/src/benchmark/select/WrtnAgentSelectBenchmark.ts
  packages/agent/src/benchmark/select/internal/WrtnAgentSelectBenchmarkReporter.ts
  packages/agent/src/internal/MathUtil.ts
  packages/agent/src/internal/TokenUsageComputer.ts
  packages/agent/src/module.ts
  packages/agent/src/structures/IWrtnAgentContext.ts
  packages/agent/src/structures/IWrtnAgentPrompt.ts
  packages/agent/test/features/test_benchmark_select.ts
Labels: documentation, enhancement

#41 Example of selection benchmark
  packages/agent/examples/benchmarks/select/README.md
  packages/agent/examples/benchmarks/select/order/1.success.md
  packages/agent/examples/benchmarks/select/order/10.success.md
  packages/agent/examples/benchmarks/select/order/2.success.md
  packages/agent/examples/benchmarks/select/order/3.success.md
  packages/agent/examples/benchmarks/select/order/4.success.md
  packages/agent/examples/benchmarks/select/order/5.success.md
  packages/agent/examples/benchmarks/select/order/6.success.md
  packages/agent/examples/benchmarks/select/order/7.success.md
  packages/agent/examples/benchmarks/select/order/8.success.md
  packages/agent/examples/benchmarks/select/order/9.success.md
  packages/agent/examples/benchmarks/select/order/README.md
  packages/agent/src/benchmark/select/IWrtnAgentSelectBenchmarkEvent.ts
  packages/agent/src/benchmark/select/WrtnAgentSelectBenchmark.ts
  packages/agent/src/benchmark/select/internal/WrtnAgentSelectBenchmarkReporter.ts
  packages/agent/test/features/test_benchmark_select.ts
  typos.toml
Labels: documentation, enhancement

#42 `IWrtnAgentExecutor` for internal agent customization
  README.md
  packages/agent/package.json
  packages/agent/src/WrtnAgent.ts
  packages/agent/src/chatgpt/ChatGptAgent.ts
  packages/agent/src/chatgpt/ChatGptCallFunctionAgent.ts
  packages/agent/src/module.ts
  packages/agent/src/structures/IWrtnAgentConfig.ts
  packages/agent/src/structures/IWrtnAgentExecutor.ts
  packages/agent/src/structures/IWrtnAgentProps.ts
  packages/agent/test/features/test_benchmark_select.ts
Labels: documentation, enhancement

#43 Fix `IWrtnAgentController.IClass.execute` type.
  packages/agent/package.json
  packages/agent/src/structures/IWrtnAgentController.ts
Labels: bug, enhancement

#47 fix(#45): wrong configured benchmark WrtnAgentBenchmarkPredicator success implementation
  packages/agent/src/benchmark/call/WrtnAgentCallBenchmark.ts
  packages/agent/src/benchmark/common/WrtnAgentBenchmarkPredicator.ts
  packages/agent/test/features/test_benchmark_predicator.ts
  packages/agent/test/features/test_benchmark_predicator_simple_allof.ts
Labels: bug

#49 Do not test LLM token required feature on Github Actions
  packages/agent/package.json
  packages/agent/test/features/test_base_event.ts
  packages/agent/test/features/test_base_websocket.ts
  packages/agent/test/features/test_base_work.ts
  packages/agent/test/features/test_benchmark_call.ts
  packages/agent/test/features/test_benchmark_predicator.ts
  packages/agent/test/features/test_benchmark_predicator_simple_allof.ts
  packages/agent/test/features/test_benchmark_select.ts
  packages/agent/test/index.ts
Labels: documentation, enhancement

#54 Detailed `IAgenticaTokenUsage`
  package.json
  packages/benchmark/src/AgenticaCallBenchmark.ts
  packages/benchmark/src/AgenticaSelectBenchmark.ts
  packages/benchmark/src/internal/AgenticaCallBenchmarkReporter.ts
  packages/benchmark/src/internal/AgenticaSelectBenchmarkReporter.ts
  packages/benchmark/src/utils/TokenUsageComputer.ts
  packages/core/src/Agentica.ts
  packages/core/src/chatgpt/ChatGptCallFunctionAgent.ts
  packages/core/src/internal/AgenticaCostAggregator.ts
  packages/core/src/internal/AgenticaTokenUsageAggregator.ts
  packages/core/src/structures/IAgenticaTokenUsage.ts
  packages/core/src/typings/AgenticaSource.ts
  test/package.json
Labels: enhancement

#58 fix: typo of `converstate`
  packages/core/src/Agentica.ts
Labels: documentation

#59 Concise README, and change `IAgenticaTokenUsage`
  README.md
  package.json
  packages/core/src/internal/AgenticaTokenUsageAggregator.ts
  packages/core/src/structures/IAgenticaTokenUsage.ts
Labels: documentation, enhancement

#63 feat: Agnetica should support third party cloud hosting
  packages/core/src/structures/IAgenticaProvider.ts
Labels: enhancement
