Repository wrtnlabs/agentica, pull requests merged in 2025-04, with the labels that each got.

#292 feat(core): `orchestrate` namespaced export
  packages/benchmark/src/AgenticaCallBenchmark.ts
  packages/benchmark/src/AgenticaSelectBenchmark.ts
  packages/chat/src/movies/AgenticaChatMovie.tsx
  packages/core/src/Agentica.ts
  packages/core/src/constants/AgenticaConstant.ts
  packages/core/src/constants/AgenticaDefaultPrompt.ts
  packages/core/src/constants/AgenticaSystemPrompt.ts
  packages/core/src/context/internal/AgenticaOperationComposer.ts
  packages/core/src/factory/events.ts
  packages/core/src/factory/prompts.ts
  packages/core/src/index.ts
  packages/core/src/orchestrate/ChatGptHistoryDecoder.ts
  packages/core/src/orchestrate/call.ts
  packages/core/src/orchestrate/cancel.ts
  packages/core/src/orchestrate/describe.ts
  packages/core/src/orchestrate/execute.ts
  packages/core/src/orchestrate/index.ts
  packages/core/src/orchestrate/initialize.ts
  packages/core/src/orchestrate/internal/cancelFunction.ts
  packages/core/src/orchestrate/internal/selectFunction.ts
  packages/core/src/orchestrate/select.ts
  packages/core/src/transformers/AgenticaEventTransformer.ts
  packages/core/src/utils/AsyncQueue.ts
  packages/core/src/utils/ByteArrayUtil.ts
  packages/core/src/utils/ChatGptCompletionMessageUtil.ts
  packages/core/src/utils/ChatGptTokenUsageAggregator.ts
  packages/core/src/utils/MPSC.ts
  packages/core/src/utils/MathUtil.ts
  packages/core/src/utils/Singleton.ts
  packages/core/src/utils/StreamUtil.ts
  packages/core/src/utils/__map_take.ts
  packages/core/src/utils/index.ts
  packages/pg-vector-selector/src/AgenticaPgVectorSelector.ts
  test/src/features/unit/async_queue/test_async_queue_base.ts
  test/src/features/unit/mpsc/test_mpsc_base.ts
  test/src/features/unit/mpsc/test_mpsc_wait_close.ts
  test/src/features/unit/stream/test_stream_reduce.ts
  test/src/features/unit/stream/test_stream_reduce_async.ts
  test/src/features/unit/stream/test_stream_to.ts
  test/src/features/unit/stream/test_stream_transform.ts
Labels: enhancement

#295 fix(cli): add runCommand function and prepare script
  packages/cli/src/commands/start.ts
  packages/cli/src/packages.ts
Labels: bug

#296 fix: fix the order of packagemanger install
  packages/cli/src/commands/start.ts
Labels: bug

#299 fix(cli): move the prepare logic
  packages/cli/src/commands/start.ts
Labels: bug

#303 fix(core): prepare command error
  packages/core/build/prompt.js
Labels: bug

#313 Related chapters
  website/content/docs/related/autoview.mdx
  website/content/docs/related/os.mdx
  website/public/images/docs/related/autoview.png
Labels: documentation

#311 fix(*): Introduce pnpm catalog
  packages/benchmark/package.json
  packages/chat/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/pg-vector-selector/package.json
  packages/rpc/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test/package.json
  website/package.json
Labels: enhancement

#327 Prepare dependabot.
  .github/dependabot.yml
  packages/benchmark/package.json
  packages/chat/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/pg-vector-selector/package.json
  packages/rpc/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test/package.json
  test/src/features/test_base_work_describe.ts
Labels: enhancement

#331 feat(core): bump up `@samchon/openapi` and `typia`
  .github/dependabot.yml.bak
  packages/chat/package.json
  packages/core/package.json
  packages/pg-vector-selector/package.json
  packages/rpc/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test/package.json
Labels: enhancement, dependencies

#334 fix(chat): wrong void statements before async function.
  packages/chat/src/examples/shopping/index.tsx
  packages/chat/src/examples/uploader/AgenticaChatPlaygroundApplication.tsx
  packages/chat/src/movies/AgenticaChatMovie.tsx
  packages/core/src/Agentica.ts
  packages/core/src/orchestrate/call.ts
  packages/core/src/orchestrate/describe.ts
  packages/core/src/orchestrate/initialize.ts
  packages/core/src/orchestrate/internal/selectFunction.ts
  packages/pg-vector-selector/src/AgenticaPgVectorSelector.ts
Labels: bug

#335 fix(chat): wrong void statement again
  packages/chat/src/examples/uploader/AgenticaChatPlaygroundApplication.tsx
  packages/chat/src/movies/AgenticaChatMovie.tsx
Labels: bug

#336 fix(core): `AgenticaCancelHistory`
  packages/benchmark/src/internal/AgenticaBenchmarkPredicator.ts
  packages/core/src/Agentica.ts
  packages/core/src/MicroAgentica.ts
  packages/core/src/context/AgenticaCancelPrompt.ts
  packages/core/src/factory/histories.ts
  packages/core/src/histories/AgenticaHistory.ts
  packages/core/src/orchestrate/call.ts
  packages/core/src/orchestrate/cancel.ts
  packages/core/src/transformers/AgenticaHistoryTransformer.ts
Labels: bug, enhancement

#339 test(rpc): check websocket's serialization
  packages/rpc/src/AgenticaRpcService.ts
  packages/rpc/src/IAgenticaRpcListener.ts
  test/src/features/rpc/test_rpc_websocket_call.ts
  test/src/features/rpc/test_rpc_websocket_initialize.ts
Labels: enhancement

#341 fix(chat): swagger uploader's headers editor
  packages/chat/package.json
  packages/chat/src/examples/shopping/index.tsx
  packages/chat/src/examples/uploader/AgenticaChatPlaygroundApplication.tsx
  pnpm-lock.yaml
Labels: bug, enhancement

#342 No assert chat completion chunk
  packages/core/src/utils/ChatGptCompletionMessageUtil.ts
Labels: bug, enhancement

#348 fix(core): not to emit select history from `MicroAgentica`.
  package.json
  packages/core/src/orchestrate/call.ts
  packages/core/src/orchestrate/cancel.ts
  packages/core/src/orchestrate/execute.ts
  packages/core/src/orchestrate/internal/cancelFunction.ts
  test/src/features/test_micro_agentica.ts
Labels: bug, enhancement

#349 feat(rpc): support `MicroAgentica in WebSocket
  packages/core/src/index.ts
  packages/rpc/src/IMicroAgenticaRpcListener.ts
  packages/rpc/src/MicroAgenticaRpcService.ts
  packages/rpc/src/index.ts
  test/src/features/rpc/test_rpc_micro_call.ts
Labels: enhancement

#350 Fix(core): bug of streaming (openrouter only)
  packages/core/src/Agentica.ts
  packages/core/src/MicroAgentica.ts
  packages/core/src/orchestrate/call.ts
  packages/core/src/orchestrate/cancel.ts
  packages/core/src/orchestrate/initialize.ts
  packages/core/src/orchestrate/select.ts
  test/src/TestGlobal.ts
  test/src/features/bugs/test_bug_openrouter_streaming.ts
Labels: bug

#353 feat(core): Change the difficult stream to a more familiar generator.
  packages/core/src/Agentica.ts
  packages/core/src/MicroAgentica.ts
  packages/core/src/events/AgenticaDescribeEvent.ts
  packages/core/src/events/AgenticaResponseEvent.ts
  packages/core/src/events/AgenticaTextEvent.ts
  packages/core/src/factory/events.ts
  packages/core/src/orchestrate/call.ts
  packages/core/src/orchestrate/describe.ts
  packages/core/src/orchestrate/initialize.ts
  packages/core/src/orchestrate/select.ts
  packages/core/src/transformers/AgenticaEventTransformer.ts
  packages/core/src/utils/StreamUtil.ts
  test/src/features/test_base_streaming.ts
  test/src/features/test_base_streaming_describe.ts
  test/src/features/unit/stream/test_stream_from.ts
Labels: enhancement

#357 fix(core): emergent bug patch for browser.
  packages/core/src/functional/assertMcpLlmApplication.ts
Labels: bug

#359 doc(core): concised description about `MicroAgentica`
  website/content/docs/concepts/function-calling.mdx
  website/content/docs/core/_meta.ts
  website/content/docs/core/event.mdx
  website/content/docs/core/facade.mdx
  website/content/docs/core/index.mdx
  website/content/docs/core/micro.mdx
  website/content/snippets/MicroAgenticaSnippet.mdx
Labels: documentation, enhancement

#361 Writing function controllers chapters
  pnpm-lock.yaml
  website/.gitignore
  website/content/docs/concepts/document-driven-development.mdx
  website/content/docs/core/_meta.ts
  website/content/docs/core/controller/_meta.ts
  website/content/docs/core/controller/mcp.mdx
  website/content/docs/core/controller/swagger.mdx
  website/content/docs/core/controller/typescript.mdx
  website/content/docs/core/facade.mdx
  website/content/docs/core/vendor.mdx
  website/content/snippets/AgenticaExampleVendorChatGptSnippet.mdx
  website/content/snippets/AgenticaExampleVendorClaudeSnippet.mdx
  website/content/snippets/AgenticaExampleVendorDeepSeekSnippet.mdx
  website/content/snippets/AgenticaExampleVendorGeminiSnippet.mdx
  website/content/snippets/AgenticaExampleVendorLlamaSnippet.mdx
  website/content/snippets/AgenticaExampleVendorMistralSnippet.mdx
  website/content/snippets/DocumentationStrategyDtoDescriptionSnippet.mdx
  website/content/snippets/DocumentationStrategyNamespaceSnippet.mdx
  website/content/snippets/DocumentationStrategyPropertyDescriptionSnippet.mdx
  website/content/snippets/OpenApiDiagramSnippet.mdx
  website/package.json
Labels: documentation

#364 docs(website): some videos
  website/content/docs/core/controller/swagger.mdx
  website/content/docs/core/controller/typescript.mdx
  website/content/docs/index.mdx
  website/content/docs/plugins/openai-vector-store.mdx
Labels: documentation, enhancement

#365 feat(website): remove "/" from Agent OS Link
  website/app/_components/landing/PreviewSection.tsx
Labels: documentation

#355 test(core): add unit test for solidity
  packages/core/src/utils/AsyncQueue.spec.ts
  packages/core/src/utils/AsyncQueue.ts
  packages/core/src/utils/MPSC.spec.ts
  packages/core/src/utils/StreamUtil.spec.ts
  test/src/features/unit/async_queue/test_async_queue_base.ts
  test/src/features/unit/mpsc/test_mpsc_base.ts
  test/src/features/unit/mpsc/test_mpsc_wait_close.ts
  test/src/features/unit/stream/test_stream_from.ts
  test/src/features/unit/stream/test_stream_reduce.ts
  test/src/features/unit/stream/test_stream_reduce_async.ts
  test/src/features/unit/stream/test_stream_transform.ts
Labels: enhancement

#376 feat(website): split react native tutorial
  website/content/tutorial/_meta.ts
  website/content/tutorial/coding/_meta.ts
  website/content/tutorial/react-native/_meta.ts
  website/content/tutorial/react-native/battery.mdx
  website/content/tutorial/react-native/calendar.mdx
  website/content/tutorial/react-native/sms.mdx
Labels: documentation, enhancement

#383 Add article link
  website/public/articles/everything-about-ai-function-calling-and-mcp-the-keyword-to-agentic-ai.html
Labels: documentation

#387 feat(core): add validation feedback to MCP controllers.
  packages/chat/src/examples/bbs/BbsChatApplication.tsx
  packages/core/src/context/AgenticaOperation.ts
  packages/core/src/context/internal/AgenticaOperationComposer.spec.ts
  packages/core/src/context/internal/AgenticaOperationComposer.ts
  packages/core/src/functional/assertMcpController.ts
  packages/core/src/functional/assertMcpLlmApplication.ts
  packages/core/src/index.ts
  packages/core/src/orchestrate/call.ts
  packages/core/src/structures/IAgenticaController.ts
  packages/core/src/structures/mcp/IMcpLlmApplication.ts
  packages/core/src/structures/mcp/IMcpLlmFunction.ts
  packages/core/src/structures/mcp/index.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test/src/features/test_base_mcp_work_describe.ts
  website/content/docs/core/controller/mcp.mdx
Labels: documentation, enhancement

#392 feat(website): change logo
  README.md
  packages/benchmark/README.md
  packages/cli/README.md
  packages/core/README.md
  packages/rpc/README.md
  website/public/logo.png
  website/public/og.jpg
Labels: documentation

#394 feat(website): change logo
  website/public/logo.png
  website/public/og.jpg
Labels: documentation

#395 Revise README for star gaining
  README.md
Labels: documentation, enhancement

#397 Change logo again
  website/public/logo.png
  website/public/og.jpg
Labels: documentation

#403 feat(website): zebra logo
  README.md
  website/public/logo.png
  website/public/og.jpg
Labels: documentation

#406 feat(core): option for disabling describe agent
  packages/core/src/MicroAgentica.ts
  packages/core/src/orchestrate/execute.ts
  packages/core/src/structures/IAgenticaExecutor.ts
  packages/core/src/structures/IMicroAgenticaExecutor.ts
Labels: enhancement

#407 feat(core): make initialize as default false
  packages/core/src/orchestrate/execute.ts
  packages/core/src/structures/IAgenticaExecutor.ts
  packages/core/src/structures/IMicroAgenticaExecutor.ts
Labels: enhancement
