Repository wrtnlabs/agentica, pull requests merged in 2025-05, with the labels that each got.

#422 feat(core): use `import()` type in MCP.
  packages/core/eslint.config.mts
  packages/core/package.json
  packages/core/src/functional/assertMcpController.ts
  packages/core/src/functional/validateMcpController.ts
  packages/core/src/structures/IAgenticaController.ts
  packages/core/src/structures/mcp/IMcpLlmTransportProps.ts
  packages/core/src/structures/mcp/index.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: enhancement

#423 feat(core): description about `@ts-ignore`
  packages/core/src/functional/assertMcpController.ts
  packages/core/src/functional/validateMcpController.ts
  packages/core/src/structures/IAgenticaController.ts
Labels: documentation

#439 Detailing README documentation chatper (requested by PMs)
  README.md
Labels: documentation

#440 docs: redesign README.md
  README.md
Labels: documentation, enhancement, good first issue

#446 feat(website): polyfill WebAssembly for `pagefind`.
  pnpm-lock.yaml
  website/app/layout.jsx
  website/package.json
Labels: documentation, enhancement

#449 feat(core): new type `systemMessage`.
  packages/benchmark/src/internal/AgenticaPromptReporter.ts
  packages/chat/src/movies/messages/AgenticaChatMessageMovie.tsx
  packages/chat/src/movies/messages/AgenticaChatSystemMessageMovie.tsx
  packages/chat/tsconfig.app.tsbuildinfo
  packages/chat/tsconfig.node.tsbuildinfo
  packages/core/src/events/AgenticaEvent.type.ts
  packages/core/src/factory/histories.ts
  packages/core/src/histories/AgenticaHistory.ts
  packages/core/src/histories/AgenticaSystemMessageHistory.ts
  packages/core/src/histories/index.ts
  packages/core/src/json/IAgenticaHistoryJson.ts
  packages/core/src/transformers/transformHistory.ts
Labels: documentation, enhancement

#451 feat(core): token usage binding
  packages/core/src/Agentica.ts
  packages/core/src/MicroAgentica.ts
  packages/core/src/context/AgenticaTokenUsage.ts
  packages/core/src/structures/IAgenticaProps.ts
  packages/core/src/structures/IMicroAgenticaProps.ts
Labels: documentation, enhancement

#452 feat(core): force function calling in validation feedback process
  packages/core/src/orchestrate/call.ts
  packages/core/src/orchestrate/cancel.ts
  packages/core/src/orchestrate/select.ts
Labels: bug, enhancement

#453 feat(agent): post build script for `@ts-ignore`.
  benchmark/vector-selector-benchmark/package.json
  packages/cli/package.json
  packages/core/build/post.js
  packages/core/eslint.config.mts
  packages/core/package.json
  packages/core/src/functional/assertMcpController.ts
  packages/core/src/functional/validateMcpController.ts
  packages/core/src/structures/IAgenticaController.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test/package.json
Labels: documentation, enhancement

#448 docs: append FAQ on README.md
  README.md
Labels: documentation
