Repository wrtnlabs/agentica, pull requests merged in 2025-03, with the labels that each got.

#69 LLM service provider becomes vendor.
  README.md
  articles/new-backend-development-paradigm-in-the-new-ai-era.md
  package.json
  packages/benchmark/README.md
  packages/benchmark/src/internal/AgenticaBenchmarkPredicator.ts
  packages/core/README.md
  packages/core/src/Agentica.ts
  packages/core/src/index.ts
  packages/core/src/structures/IAgenticaContext.ts
  packages/core/src/structures/IAgenticaEvent.ts
  packages/core/src/structures/IAgenticaProps.ts
  packages/core/src/structures/IAgenticaTokenUsage.ts
  packages/core/src/structures/IAgenticaVendor.ts
  test/src/cli.ts
  test/src/features/test_base_event.ts
  test/src/features/test_base_websocket.ts
  test/src/features/test_base_work.ts
  test/src/features/test_benchmark_call.ts
  test/src/features/test_benchmark_predicator.ts
  test/src/features/test_benchmark_predicator_simple_allof.ts
  test/src/features/test_benchmark_select.ts
Labels: documentation, enhancement

#70 Utilize `IHttpLlmFunction.validate()` function
  packages/core/README.md
  packages/core/src/chatgpt/ChatGptCallFunctionAgent.ts
  packages/core/src/structures/IAgenticaController.ts
  packages/core/src/structures/IAgenticaOperation.ts
  packages/core/src/structures/IAgenticaOperationSelection.ts
  packages/core/src/structures/IAgenticaPrompt.ts
Labels: enhancement

#71 New package `@agentica/chat`
  README.md
  deploy/internal/loadPackages.js
  deploy/publish.js
  package.json
  packages/chat/.gitignore
  packages/chat/LICENSE
  packages/chat/README.md
  packages/chat/bbs/index.html
  packages/chat/build/deploy.mjs
  packages/chat/eslint.config.js
  packages/chat/index.html
  packages/chat/package.json
  packages/chat/playground/index.html
  packages/chat/rollup.config.cjs
  packages/chat/shopping/index.html
  packages/chat/src/AgenticaChatApplication.tsx
  packages/chat/src/README.md
  packages/chat/src/components/MarkdownViewer.tsx
  packages/chat/src/examples/bbs/BbsArticleService.ts
  packages/chat/src/examples/bbs/BbsChatApplication.tsx
  packages/chat/src/examples/bbs/IBbsArticle.ts
  packages/chat/src/examples/bbs/index.tsx
  packages/chat/src/examples/bbs/script.md
  packages/chat/src/examples/index.tsx
  packages/chat/src/examples/playground/AgenticaChatPlaygroundApplication.tsx
  packages/chat/src/examples/playground/AgenticaChatPlaygroundFileUploadMovie.tsx
  packages/chat/src/examples/playground/index.tsx
  packages/chat/src/examples/shopping/ShoppingChatApplication.tsx
  packages/chat/src/examples/shopping/index.tsx
  packages/chat/src/examples/shopping/script.md
  packages/chat/src/index.ts
  packages/chat/src/movies/AgenticaChatMovie.tsx
  packages/chat/src/movies/messages/AgenticaChatDescribeMessageMovie.tsx
  packages/chat/src/movies/messages/AgenticaChatExecuteMessageMovie.tsx
  packages/chat/src/movies/messages/AgenticaChatMessageMovie.tsx
  packages/chat/src/movies/messages/AgenticaChatSelectMessageMovie.tsx
  packages/chat/src/movies/messages/AgenticaChatTextMessageMovie.tsx
  packages/chat/src/movies/sides/AgenticaChatFunctionStackSideMovie.tsx
  packages/chat/src/movies/sides/AgenticaChatSideMovie.tsx
  packages/chat/src/movies/sides/AgenticaChatTokenUsageSideMovie.tsx
  packages/chat/tsconfig.app.json
  packages/chat/tsconfig.app.tsbuildinfo
  packages/chat/tsconfig.json
  packages/chat/tsconfig.lib.json
  packages/chat/tsconfig.node.json
  packages/chat/tsconfig.node.tsbuildinfo
  packages/chat/vite-env.d.ts
  packages/chat/vite.config.ts
  prettier.config.js
Labels: documentation, enhancement

#72 Guide NestJS WebSocket integration
  README.md
  packages/rpc/README.md
Labels: documentation

#76 Fix examples link
  package.json
  packages/chat/src/examples/index.tsx
Labels: documentation

#85 Publish website, and fill contents later
  .github/workflows/website.yml
  .vscode/settings.json
  articles/typia-accomplished-agentic-ai-with-typescript-compiler-enhanced-function-calling.md
  website/.gitignore
  website/app/[[...mdxPath]]/page.jsx
  website/app/layout.jsx
  website/build/deploy.js
  website/build/playground.js
  website/build/sitemap.js
  website/content/_meta.ts
  website/content/docs/_meta.ts
  website/content/docs/autoview.mdx
  website/content/docs/core/_meta.ts
  website/content/docs/core/class.mdx
  website/content/docs/core/index.mdx
  website/content/docs/core/swagger.mdx
  website/content/docs/function-calling.mdx
  website/content/docs/index.mdx
  website/content/docs/os.mdx
  website/content/docs/plugins/_meta.ts
  website/content/docs/plugins/pg-vector-selector.mdx
  website/content/docs/roadmap.mdx
  website/content/docs/setup.mdx
  website/content/docs/websocket/_meta.ts
  website/content/docs/websocket/client.mdx
  website/content/docs/websocket/index.mdx
  website/content/docs/websocket/nestjs.mdx
  website/content/docs/websocket/nodejs.mdx
  website/content/index.mdx
  website/mdx-components.jsx
  website/next-env.d.ts
  website/next-sitemap.config.js
  website/next.config.ts
  website/package.json
  website/public/favicon/android-chrome-192x192.png
  website/public/favicon/android-chrome-512x512.png
  website/public/favicon/apple-touch-icon.png
  website/public/favicon/favicon-16x16.png
  website/public/favicon/favicon-32x32.png
  website/public/favicon/favicon.ico
  website/public/favicon/site.webmanifest
  website/public/images/logo.png
  website/public/images/og.png
  website/tsconfig.json
Labels: documentation, enhancement

#86 Setup docs
  website/app/layout.jsx
  website/content/docs/_meta.ts
  website/content/docs/autoview.mdx
  website/content/docs/core/_meta.ts
  website/content/docs/core/class.mdx
  website/content/docs/core/config.mdx
  website/content/docs/core/event.mdx
  website/content/docs/core/history.mdx
  website/content/docs/core/index.mdx
  website/content/docs/core/swagger.mdx
  website/content/docs/index.mdx
  website/content/docs/os.mdx
  website/content/docs/plugins/_meta.ts
  website/content/docs/plugins/openai-vector-store.mdx
  website/content/docs/plugins/pg-vector-selector.mdx
  website/content/docs/roadmap.mdx
  website/content/docs/setup.mdx
  website/content/index.mdx
  website/public/images/og.png
  website/public/logo.png
  website/public/og.jpg
Labels: documentation

#87 Writing guide documents
  README.md
  articles/i-made-mcp-alternative-solution-for-openai-and-all-other-llms.md
  packages/chat/bbs/index.html
  packages/chat/index.html
  packages/chat/shopping/index.html
  packages/chat/src/examples/index.tsx
  packages/chat/src/examples/uploader/AgenticaChatPlaygroundApplication.tsx
  packages/chat/src/examples/uploader/AgenticaChatUploaderMovie.tsx
  packages/chat/src/examples/uploader/index.tsx
  packages/chat/tsconfig.app.tsbuildinfo
  packages/chat/tsconfig.node.tsbuildinfo
  packages/chat/uploader/index.html
  packages/chat/vite.config.ts
  packages/rpc/README.md
  website/app/layout.jsx
  website/content/docs/_meta.ts
  website/content/docs/concepts/_meta.ts
  website/content/docs/concepts/compiler-driven-development.mdx
  website/content/docs/concepts/document-driven-development.mdx
  website/content/docs/concepts/function-calling.mdx
  website/content/docs/core/_meta.ts
  website/content/docs/core/class.mdx
  website/content/docs/core/swagger.mdx
  website/content/docs/plugins/_meta.ts
  website/content/docs/plugins/benchmark.mdx
  website/content/docs/related/_meta.ts
  website/content/docs/related/autoview.mdx
  website/content/docs/related/os.mdx
  website/content/docs/websocket/_meta.ts
  website/content/docs/websocket/client.mdx
  website/content/docs/websocket/index.mdx
  website/content/docs/websocket/nestjs.mdx
  website/content/docs/websocket/nodejs.mdx
Labels: documentation

#92 Benchmark chapter
  packages/benchmark/src/structures/IAgenticaSelectBenchmarkEvent.ts
  typedoc.json
  website/content/docs/plugins/benchmark.mdx
Labels: documentation, enhancement

#93 Fix wrong dependency
  package.json
  packages/rpc/package.json
Labels: bug

#97 Fix websocket problem
  package.json
  packages/core/src/context/internal/AgenticaTokenUsageAggregator.ts
  packages/rpc/src/AgenticaRpcService.ts
  packages/rpc/src/IAgenticaRpcListener.ts
  packages/rpc/src/IAgenticaRpcService.ts
  test/src/features/test_base_websocket.ts
Labels: bug

#90 feat: Agentica CLI
  packages/cli/package.json
  packages/cli/src/bases/Connector.ts
  packages/cli/src/bases/Package.ts
  packages/cli/src/bases/Tsconfig.ts
  packages/cli/src/executable/AgenticaStart.ts
  packages/cli/src/index.ts
  packages/cli/src/utils/capitalize.ts
  packages/cli/src/utils/createProjectDirectory.ts
  packages/cli/src/utils/getNpmPackages.ts
  packages/cli/src/utils/getQuestions.ts
  packages/cli/tsconfig.json
Labels: enhancement

#106 Writing websocket chapters
  test/src/examples/websocket-client-hook.ts
  test/src/examples/websocket-client-main.ts
  test/src/examples/websocket-node-separate.ts
  website/content/docs/websocket/client.mdx
  website/content/docs/websocket/nestjs.mdx
  website/content/docs/websocket/nodejs.mdx
Labels: documentation, enhancement

#105 Feat/agentica cli template
  packages/cli/src/bases/Connector.ts
  packages/cli/src/bases/Package.ts
  packages/cli/src/executable/AgenticaStart.ts
  packages/cli/src/index.ts
  packages/cli/src/structures/IAgenticaStart.ts
  packages/cli/src/structures/IAgenticaStartOption.ts
  packages/cli/src/utils/createProjectDirectory.ts
  packages/cli/src/utils/types/PackageManager.ts
  packages/cli/src/utils/types/ProjectOption.ts
Labels: enhancement

#107 Completed websocket chapters
  typos.toml
  website/content/docs/websocket/_meta.ts
  website/content/docs/websocket/client.mdx
  website/content/docs/websocket/index.mdx
  website/content/docs/websocket/nestjs.mdx
Labels: enhancement

#108 WebSocket setup summary.
  website/content/docs/websocket/index.mdx
  website/content/docs/websocket/nestjs.mdx
Labels: documentation

#111 "Core Library > Facade Controller" chapter
  website/content/docs/core/config.mdx
  website/content/docs/core/event.mdx
  website/content/docs/core/facade.mdx
  website/content/docs/core/history.mdx
  website/content/docs/core/index.mdx
Labels: documentation, enhancement

#115 Filling contents of core library chapters
  packages/core/src/context/AgenticaTokenUsage.ts
  website/build/snippet.js
  website/content/_meta.ts
  website/content/docs/core/config.mdx
  website/content/docs/core/event.mdx
  website/content/docs/core/facade.mdx
  website/content/docs/core/history.mdx
  website/content/docs/core/index.mdx
  website/content/snippets/AgenticaContextSnippet.mdx
  website/content/snippets/AgenticaEventSnippet.mdx
  website/content/snippets/AgenticaOperationSelectionSnippet.mdx
  website/content/snippets/AgenticaOperationSnippet.mdx
  website/content/snippets/AgenticaPromptSnippet.mdx
  website/content/snippets/AgenticaSnippet.mdx
  website/content/snippets/IAgenticaConfigSnippet.mdx
  website/content/snippets/IAgenticaControllerSnippet.mdx
  website/content/snippets/IAgenticaExecutorSnippet.mdx
  website/content/snippets/IAgenticaPromptJsonSnippet.mdx
  website/content/snippets/IAgenticaPropsSnippet.mdx
  website/content/snippets/IAgenticaSystemPromptSnippet.mdx
  website/content/snippets/IAgenticaVendorSnippet.mdx
  website/package.json
Labels: documentation

#127 Event and function calling chapters
  website/app/layout.jsx
  website/content/docs/concepts/function-calling.mdx
  website/content/docs/core/event.mdx
Labels: documentation

#128 Guidance of system prompt configuration
  website/content/docs/core/config.mdx
Labels: documentation

#136 Completion of core library contents
  website/content/docs/core/history.mdx
Labels: enhancement

#137 Fix some errors and contents
  .github/workflows/website.yml
  website/app/_components/landing/ChatBubble.tsx
  website/app/_components/landing/WelcomeSection.tsx
  website/app/_constants/landing.ts
Labels: bug, documentation, enhancement

#138 Detour icon bugs of landing page for a while
  website/app/_components/common/dropdown-menu.tsx
Labels: documentation

#139 Doc/landing
  website/app/_components/common/dropdown-menu.tsx
  website/app/_components/common/hover.tsx
  website/app/_components/common/link.tsx
  website/app/_components/common/navigation-menu.tsx
  website/app/_components/common/tabs.tsx
  website/tsconfig.tsbuildinfo
Labels: bug, documentation, enhancement

#140 Roadmap chapter
  website/content/docs/core/index.mdx
  website/content/docs/roadmap.mdx
Labels: documentation, enhancement

#146 Fix path addresses, and keep
  website/app/_pages/LandingPage.tsx
  website/content/_meta.ts
  website/content/tutorial/_meta.ts
  website/content/tutorial/coding/_meta.ts
  website/content/tutorial/coding/file-system.mdx
  website/content/tutorial/coding/github.mdx
  website/content/tutorial/index.mdx
  website/content/tutorial/productivity/_meta.ts
  website/content/tutorial/productivity/gmail.mdx
Labels: enhancement

#151 RemoteSource compiling dynamic MDX content
  pnpm-lock.yaml
  website/build/snippet.js
  website/components/RemoteSource.tsx
  website/content/docs/concepts/compiler-driven-development.mdx
  website/content/docs/concepts/document-driven-development.mdx
  website/content/docs/core/config.mdx
  website/content/docs/core/facade.mdx
  website/content/docs/core/history.mdx
  website/content/docs/core/index.mdx
  website/content/docs/websocket/client.mdx
  website/content/docs/websocket/index.mdx
  website/content/docs/websocket/nestjs.mdx
  website/content/docs/websocket/nodejs.mdx
  website/content/snippets/AgenticaContextSnippet.mdx
  website/content/snippets/IAgenticaConfigSnippet.mdx
  website/content/snippets/IAgenticaControllerSnippet.mdx
  website/content/snippets/IAgenticaExecutorSnippet.mdx
  website/content/snippets/IAgenticaPromptJsonSnippet.mdx
  website/content/snippets/IAgenticaPropsSnippet.mdx
  website/content/snippets/IAgenticaSystemPromptSnippet.mdx
  website/content/snippets/IAgenticaVendorSnippet.mdx
  website/package.json
  website/tsconfig.json
Labels: documentation, enhancement

#159 feat(cli): add React Template for project type
  packages/cli/src/executable/AgenticaStart.ts
  packages/cli/src/functional/AgenticaStarter.ts
  packages/cli/src/utils/getQuestions.ts
Labels: enhancement

#164 enterprise tutorial
  website/content/tutorial/_meta.ts
  website/content/tutorial/enterprise/_meta.ts
  website/content/tutorial/enterprise/shopping.mdx
  website/content/tutorial/productivity/_meta.ts
Labels: documentation

#184 Writing "Contract Driven Development" chapter
  website/content/docs/concepts/compiler-driven-development.mdx
  website/content/docs/core/index.mdx
  website/content/docs/index.mdx
  website/content/docs/plugins/benchmark.mdx
  website/content/snippets/AgenticaExampleActualSnippet.mdx
  website/content/snippets/AgenticaExamplePseudoSnippet.mdx
  website/content/snippets/KotlinSpringSnippet.mdx
  website/content/snippets/PhpLaravelSnippet.mdx
  website/content/snippets/PythonDjangoSnippet.mdx
  website/content/snippets/PythonFastApiSnippet.mdx
Labels: documentation

#199 Complete CDD
  website/content/docs/concepts/compiler-driven-development.mdx
  website/content/snippets/BbsArticleControllerSnippet.mdx
  website/content/snippets/BbsArticleServiceSnippet.mdx
  website/content/snippets/ClassValidatorSnippet.mdx
  website/content/snippets/IBbsArticleSnippet.mdx
  website/content/snippets/KotlinSpringSnippet.mdx
  website/content/snippets/LlmApplicationExampleSnippet.mdx
  website/content/snippets/LlmApplicationJavaScriptSnippet.mdx
  website/content/snippets/PhpLaravelSnippet.mdx
  website/content/snippets/PythonDjangoSnippet.mdx
  website/content/snippets/PythonFastApiSnippet.mdx
Labels: documentation, enhancement

#200 Writing document driven development
  website/content/docs/concepts/compiler-driven-development.mdx
  website/content/docs/concepts/document-driven-development.mdx
  website/content/snippets/ShoppingCustomerOrderPublishControllerSnippet.mdx
  website/content/snippets/ShoppingSaleControllerSnippet.mdx
  website/public/images/docs/concepts/agent-workflow-example.png
Labels: documentation, enhancement

#202 Document Driven Development
  website/content/docs/concepts/document-driven-development.mdx
Labels: documentation, enhancement

#209 docs(website): Update Agentica Tutorial Getting Started using cli
  website/content/tutorial/index.mdx
Labels: documentation

#217 Add gurubase chatbot
  README.md
  website/app/layout.jsx
  website/content/docs/concepts/_meta.ts
  website/content/docs/index.mdx
Labels: documentation

#220 docs(website): modify_location_of_agentica_tutorial_video
  website/content/tutorial/index.mdx
Labels: documentation

#221 Dark mode only
  README.md
  website/app/layout.jsx
  website/content/docs/concepts/_meta.ts
  website/next.config.ts
Labels: documentation

#249 fix(cli): add the help comment to cli connector question
  packages/cli/src/commands/start.ts
Labels: enhancement

#254 Bump up dependencies to avoid samchon/typia#1554
  packages/benchmark/package.json
  packages/chat/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/rpc/package.json
  pnpm-lock.yaml
  test/package.json
Labels: bug

#259 fix(cli): remove BbsArticle when select connectors in NestJS Template
  packages/cli/src/commands/start.ts
Labels: bug, enhancement

#261 docs(website): add notion agent tutorial demo video
  website/content/tutorial/productivity/notion.mdx
Labels: documentation

#269 feat(core): bump up dependencies and change http application creator type
  packages/core/src/functional/assertHttpLlmApplication.ts
  packages/core/src/functional/validateHttpLlmApplication.ts
Labels: enhancement

#270 doc(website): documentation of #253
  website/content/docs/core/facade.mdx
  website/content/docs/core/index.mdx
  website/content/docs/plugins/benchmark.mdx
  website/content/snippets/AgenticaExampleActualSnippet.mdx
  website/content/snippets/AgenticaExamplePseudoSnippet.mdx
  website/content/tutorial/coding/swagger.mdx
  website/content/tutorial/index.mdx
Labels: documentation, enhancement

#282 fix(cli): publishing config
  packages/cli/package.json
Labels: bug
